version: '3.4'

services:
  app:
    image: node:alpine
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command:  sh -c "yarn && yarn start"
    ports:
      - "3000:3000"
    environment:
      - TERM=xterm
